version: '3.4'

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  gameoflifeapi:
    image: ${DOCKER_REGISTRY-}gameoflifeapi
    build:
      context: .
      dockerfile: GameofLifeAPI/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  mongo_data:
